PACKAGE=acmart

MAINFILE = main.tex

PDF = ${MAINFILE:%.tex=%.pdf}


all:  ${PDF}

%.cls:   %.ins %.dtx  
	pdflatex $<

%.pdf:  %.tex content/*.tex   $(PACKAGE).cls ACM-Reference-Format.bst
	pdflatex $<
	- bibtex $*
	pdflatex $<
	pdflatex $<
	while ( grep -q '^LaTeX Warning: Label(s) may have changed' $*.log) \
	do pdflatex $<; done

clean:
	$(RM)  *.log *.aux \
	*.cfg *.glo *.idx *.toc \
	*.ilg *.ind *.out *.lof \
	*.lot *.bbl *.blg *.gls *.cut *.hd \
	*.dvi *.ps *.thm *.tgz *.zip *.rpi
